"""
lock_fsm.py

POSM FPGA MTS Laser Lock
Supervisory Lock State Machine

Purpose
-------
lock_fsm is the "boss" of the whole lock system. 
It coordinates everything and decides what the system should be doing 
right now. 

This module intentionally performs NO DSP.
It never processes ADC samples.
It never computes spectroscopy features.
It never participates in the MHz feedback path.
Its outputs are supervisory enables and control requests only.


IMPLEMENTATION STUFF
--------------------

States:

    IDLE            → do nothing
    WIDE_SCAN       → tell the scan module to start scanning
    TRACE_READY     → tell the system the scan is finished
    USER_SELECT     → wait for the user to choose a spectroscopy feature
    ZOOM_SCAN       → tell the scanner to zoom in
    FEATURE_VERIFY  → tell the autolock module to check the feature
    ARM_LOCK        → prepare the controller for locking
    LOCKED          → enable the fast feedback loop
    LOCK_WATCH      → keep checking if the lock is still healthy
    RELOCK_SCAN     → restart scanning if the lock is lost
    FAULT           → disable outputs and put the system in a safe state

Timing
------

Clock:
    system FPGA clock

State updates:
    synchronous, one clock per transition evaluation

Latency:
    command recognition:
        1 clock

    state transition:
        1 clock after condition evaluation


Some Important informations
---------------------------

Fault input overrides every state.

Fault clear requires:
    fault_clear_request == 1
    fault_active == 0
"""

from amaranth import *
from amaranth.lib.enum import Enum


# ---------------------------------------------------------------------
# State encoding
# ---------------------------------------------------------------------

class LockState(Enum):
    """
    This is just a list of all the possible modes the lock system can be in.
    """
    IDLE            = 0
    WIDE_SCAN       = 1
    TRACE_READY     = 2
    USER_SELECT     = 3 # For future improvements
    ZOOM_SCAN       = 4
    FEATURE_VERIFY  = 5
    ARM_LOCK        = 6
    LOCKED          = 7
    LOCK_WATCH      = 8
    RELOCK_SCAN     = 9
    FAULT           = 10


# ---------------------------------------------------------------------
# Lock FSM
# ---------------------------------------------------------------------

class LockFSM(Elaboratable):

    def __init__(self):

        # -------------------------------------------------------------
        # Inputs
        # -------------------------------------------------------------

        # Global enable from CONTROL register
        self.global_enable = Signal()

        # Host requested lock sequence
        self.lock_enable_request = Signal()

        # Host requested hold
        self.hold_request = Signal()

        # Generated by fault_gate
        # Fault always wins.
        self.fault_active = Signal()

        # Explicit fault clear request
        self.fault_clear_request = Signal()

        # Trace capture completed
        # From trace_capture.py.
        self.trace_ready = Signal()

        # User has loaded a valid autolock descriptor.
        self.feature_selected = Signal()

        # Zoom scan complete
        self.zoom_complete = Signal()

        # Robust autolock result
        self.autolock_success = Signal()
        self.autolock_failed = Signal()

        # Lock check result
        self.lock_check_pass = Signal()
        self.lock_check_failed = Signal()

        # Relock request generated by lock watch
        self.relock_request = Signal()

        # -------------------------------------------------------------
        # Outputs
        # -------------------------------------------------------------

        # Current state exposed to register bank
        self.state = Signal(LockState)

        # Scan control outputs
        self.wide_scan_enable = Signal()
        self.zoom_scan_enable = Signal()

        # Trace capture control
        self.trace_enable = Signal()

        # Robust autolock enable
        self.autolock_enable = Signal()

        # Fast controller enable
        # This only enables the existing fast controller.
        # It does NOT sit in the feedback path.
        self.feedback_enable = Signal()

        # Lock watch enable
        self.lock_watch_enable = Signal()

        # Fault state output
        self.fault_state = Signal()


    # -----------------------------------------------------------------
    # RTL
    # -----------------------------------------------------------------

    def elaborate(self, platform):

        m = Module()

        state = Signal(LockState, reset=LockState.IDLE)

        m.d.sync += self.state.eq(state)


        # =============================================================
        # Fault priority logic
        # =============================================================

        with m.If(self.fault_active):
            m.d.sync += state.eq(LockState.FAULT)


        with m.Elif(state == LockState.FAULT):

            with m.If(self.fault_clear_request):
                m.d.sync += state.eq(
                    LockState.IDLE
                )


        # =============================================================
        # Normal state machine
        # =============================================================

        with m.Elif(state == LockState.IDLE):

            with m.If(
                self.global_enable &
                self.lock_enable_request
            ):
                m.d.sync += state.eq(
                    LockState.WIDE_SCAN
                )


        with m.Elif(state == LockState.WIDE_SCAN):

            with m.If(self.trace_ready):
                m.d.sync += state.eq(
                    LockState.TRACE_READY
                )


        with m.Elif(state == LockState.TRACE_READY):

            # Wait for user/host feature selection.
            with m.If(self.feature_selected):
                m.d.sync += state.eq(
                    LockState.ZOOM_SCAN
                )


        with m.Elif(state == LockState.ZOOM_SCAN):

            with m.If(self.zoom_complete):
                m.d.sync += state.eq(
                    LockState.FEATURE_VERIFY
                )


        with m.Elif(state == LockState.FEATURE_VERIFY):

            with m.If(self.autolock_success):
                m.d.sync += state.eq(
                    LockState.ARM_LOCK
                )

            with m.Elif(self.autolock_failed):
                m.d.sync += state.eq(
                    LockState.RELOCK_SCAN
                )


        with m.Elif(state == LockState.ARM_LOCK):

            #
            # Controller initialization happens externally:
            #
            # - PI reset/load
            # - offset load
            # - polarity load
            # - safe handoff
            #
            # Once complete, lock enters watch.
            #

            with m.If(self.lock_check_pass):
                m.d.sync += state.eq(
                    LockState.LOCKED
                )


        with m.Elif(state == LockState.LOCKED):
            m.d.sync += state.eq(
                LockState.LOCK_WATCH
            )


        with m.Elif(state == LockState.LOCK_WATCH):

            with m.If(self.lock_check_failed || self.relock_request):
                m.d.sync += state.eq(
                    LockState.RELOCK_SCAN
                )

        with m.Elif(state == LockState.RELOCK_SCAN):
            # Relock policy is configured elsewhere: FEATURE_VERIFY
            # This state represents:
            # "begin acquisition again"
            m.d.sync += state.eq(
                LockState.ZOOM_SCAN
            )


        # =============================================================
        # Output decoding
        # =============================================================

        with m.Switch(state):

            with m.Case(LockState.WIDE_SCAN):
                m.d.comb += [
                    self.wide_scan_enable.eq(1),
                    self.trace_enable.eq(1),
                ]


            with m.Case(LockState.ZOOM_SCAN):
                m.d.comb += [
                    self.zoom_scan_enable.eq(1),
                    self.trace_enable.eq(1),
                ]


            with m.Case(LockState.FEATURE_VERIFY):
                m.d.comb += [
                    self.autolock_enable.eq(1),
                ]


            with m.Case(LockState.ARM_LOCK):
                m.d.comb += [
                    self.feedback_enable.eq(1),
                ]


            with m.Case(LockState.LOCKED):
                m.d.comb += [
                    self.feedback_enable.eq(1),
                ]


            with m.Case(LockState.LOCK_WATCH):
                m.d.comb += [
                    self.feedback_enable.eq(1),
                    self.lock_watch_enable.eq(1),
                ]


            with m.Case(LockState.FAULT):
                m.d.comb += [
                    self.fault_state.eq(1),
                ]

        return m